# Faker - Synthetic User Data
In this exercise I'm generating a DataFrame full of authentic german user data using the faker library.

In [7]:
import pandas as pd
from faker import Faker

In [115]:
df = pd.DataFrame(columns=["USER_ID", "FIRSTNAME", "LASTNAME", "STREET", "HOUSENUMBER", "ZIPCODE", "CITY", "LAT", "LON", "PREFERENCE", "CURRENCY", "TIMEZONE"])

fake = Faker("de_DE")

word_list = ["loves", "hates", "buyes", "does not buy", "steals", "borrows", "Salat", "Steak", "Carots"]

for row in range(0,10):
    fake_results = []
    fake_results.append(fake.unique.random_int(min=1, max=100))
    fake_results.append(fake.unique.first_name())
    fake_results.append(fake.last_name())
    fake_results.append(fake.street_name())
    fake_results.append(fake.random_int(min=1, max=127))
    fake_results.append(fake.postcode())
    fake_results.append(fake.city_name())  
    fake_results.append(fake.latitude())
    fake_results.append(fake.longitude())
    fake_results.append(fake.sentence(ext_word_list=word_list))
    fake_results.append(fake.currency_symbol())
    fake_results.append(fake.timezone())
    df.loc[len(df)] = fake_results

df.head(10)

,USER_ID,FIRSTNAME,LASTNAME,STREET,HOUSENUMBER,ZIPCODE,CITY,LAT,LON,PREFERENCE,CURRENCY,TIMEZONE
0,92,Alf,Berger,Michelle-Vollbrecht-Weg,34,48315,Nauen,-88.4731275,-145.996102,Buyes Salat loves steals.,$,America/St_Kitts
1,21,Fernando,Aumann,Ernstweg,119,50743,Genthin,-13.0014685,177.260550,Hates Salat Salat steals steals buyes borrows.,ƒ,Africa/Brazzaville
2,22,Milena,Mülichen,Vittorio-Mülichen-Gasse,95,00173,Lippstadt,-22.9525145,-39.580939,Carots Salat hates Steak.,Lev,Asia/Tashkent
3,45,Theodora,Hoffmann,Klingelhöferstraße,67,81972,Malchin,50.425525,-84.409148,Borrows Carots buyes buyes.,Fr,Asia/Ashgabat
4,86,Linus,Dobes,Heckerstr.,29,05111,Saarlouis,-70.166797,153.547684,Buyes borrows Salat Salat does not buy loves S...,leu,Africa/Lubumbashi
5,62,Steve,Gertz,Kargestraße,95,15161,Ansbach,-32.1744655,67.482616,Loves loves borrows steals.,£,Europe/Zaporozhye
6,32,Micha,Jockel,Marko-Pruschke-Allee,125,66130,Dachau,41.208748,90.426703,Hates Carots hates hates borrows steals.,$,Europe/Tallinn
7,69,Elke,Jacob,Döringplatz,52,02953,Nördlingen,71.598982,-80.866144,Carots Salat hates Salat.,Fr,America/Nassau
8,65,Nikolaj,Keudel,Sabrina-Döhn-Allee,61,93588,Rosenheim,61.676653,27.117952,Steals Salat Carots does not buy borrows.,£,America/Bogota
9,2,Oxana,Liebelt,Astrid-Weller-Ring,17,04347,Neuruppin,-22.3214765,-155.603338,Salat hates buyes.,F,Australia/Perth